list = {
    'Settings': 'Настройки',
    'DesktopSettings': 'Настройки рабочего стола',
    'Database': 'Базы данных',
    'Development': 'Разработка',
    'Graphics': 'Графика',
    'Viewer': 'Просмотрщики',
    'Photography': 'Фотография',
    'Network': 'Сеть',
    'WebBrowser': 'Браузеры',
    'Utility': 'Утилиты',
    'Archiving': 'Архиваторы',
    'Compression': 'Архиваторы',
    'ConsoleOnly': 'Консольные',
    'System': 'Системные',
    'TerminalEmulator': 'Терминалы',
    '2DGraphics': '2D Графика',
    'Debugger': 'Отладка',
    'FileTransfer': 'Передача файлов',
    'TextEditor': 'Текстовые редакторы',
    'Application': 'Программы',
    'Applications': 'Программы',
    'AudioVideo': 'Мультимедия',
    'Audio': 'Звук',
    'Video': 'Видео',
    'Game': 'Игры',
    'Documentation': 'Документация',
    'Player': 'Проигрываетльи',
    'Recorder': 'Запись',
    'AdvancedSettings': 'Доп. Настройки',
    'FileManager': "Файлове менеджеры"
    }